version: '3'
services:
  web:
    image: akraradets/soil-web:v0.0.1
    build:
      context: .
      dockerfile: web.Dockerfile
    ports:
      - 9000:80
    volumes:
      - vscode-web:/root/.vscode-server
      # - ./soid:/var/www/html
  api:
    image: akraradets/soil-api:v0.0.01
    build:
      context: .
      dockerfile: api.Dockerfile
    command: tail -f /dev/null
    # command: uvicorn main:app --reload --host=0.0.0.0 --port=80
    ports:
      - 9001:80
    volumes:
      - vscode-api:/root/.vscode-server
      - ./api:/root/projects
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
  dev:
    build:
      context: .
      dockerfile: dev.Dockerfile
    # restart: always
    shm_size: '16gb'
    volumes:
      - vscode-dev:/root/.vscode-server
      - ./pytorch:/root/projects
    env_file:
      - .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  vscode-dev:
  vscode-web:
  vscode-api: