version: '3'
services:
  pytorch:
    hostname: 'pytorch.soil'
    build:
      context: .
      dockerfile: pytorch.Dockerfile
    # restart: always
    shm_size: '16gb'
    ports: 
      - 8000:8000
    volumes:
      - ./pytorch.vscode-server:/root/.vscode-server
      - ./pytorch/:/root/projects
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]