version: '3'
services:
  web:
    image: akraradets/soil-web:v0.0.1
    build:
      context: .
      dockerfile: web.Dockerfile
    ports:
      - 9000:80
    volumes:
      - vscode-web:/root/.vscode-server
      - ./soid:/var/www/html
  dev:
    build:
      context: .
      dockerfile: dev.Dockerfile
    # restart: always
    shm_size: '16gb'
    volumes:
      - vscode-dev:/root/.vscode-server
      - ./pytorch:/root/projects
    env_file:
      - .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  vscode-dev:
  vscode-web: