name: BuildNPush to GitHub Container Registry
run-name: ${{ github.actor }} created ${{ github.ref }}

on:
  push:
    tags:
        - 'v*'

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5.1.0
        with:
          # Your image name
          images: ghcr.io/${{ github.actor }}/${{ vars.IMAGE_NAME }}
          tags: type=semver,pattern={{raw}}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            BUILD_VERSION=${{ github.ref_name }}
          labels: |
            org.opencontainers.image.source=${{ vars.LABEL_SOURCE }}
            org.opencontainers.image.licenses=MIT
